name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: wechat-enhancer-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          app/build/outputs/logs/
          app/build/reports/
          
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: wechat-enhancer-release-apk
        path: app/build/outputs/apk/release/app-release.apk